Update grpc.md
Yurunsoft/imi pull request #393
Opened 2022-07-26 02:35 UTC by Hammer-7

完善文档

2022-07-26 03:26 UTC, Yurunsoft commented on doc/components/rpc/grpc.md
> +`config.php` 配置忽略目录
这边要加换行

2022-07-26 03:26 UTC, Yurunsoft commented on doc/components/rpc/grpc.md
> +```
应该是：
```md
```php
```

2022-07-27 04:11 UTC, sy-records requested changes

2022-07-27 04:11 UTC, sy-records commented on doc/components/rpc/grpc.md
> +```
```suggestion

`config.php` 配置忽略目录

```php
```

2022-07-27 05:59 UTC, sy-records approved these changes

2022-07-27 06:14 UTC, merged